Fix reading transformable class bytes loaded by AppClassLoader
McModLauncher/securejarhandler pull request #28
Opened 2022-03-26 22:48 UTC by Su5eD

#### The issue
As reported in #27, ModuleClassLoader fails to read bytes of libraries on the java boot module layer used in transformers. This happens because it's trying to find resources on the PlatformClassLoader instead of the AppClassLoader.
See [here](https://github.com/McModLauncher/securejarhandler/issues/27#issuecomment-998171355) for a full explanation of the issue by @sciwhiz12.

#### The solution
Quote from sciwhiz's explanation:
> Therefore, the solution is that the above error be corrected by changing the use of `ClassLoader.getPlatformClassLoader()` to `ClassLoader.getSystemClassLoader()` instead, so the resolution of class bytes for ASM, SJH, and BSL (or any other class whose module is in the ignore list configured in BSL and exists on the application class loader) works as expected.

2022-03-28 07:12 UTC, OrionDevelopment commented
@Su5eD How have you tested that this won't be causing any issues down the line with classpath collisions?

2022-03-28 17:43 UTC, Su5eD commented
The system classloader primarily looks for class resources (e.g. those containing a fully qualified class name, such as `cpw/mods/niofs/union/UnionFileSystem.class`) in the class' module, so the read resource is always identical to the loaded class. In case a class from an unnamed module is used in a transformer, reading it will be successful, although the game will crash if it ever tries to load the class. This, however, shouldn't happen with our current setup.

Alternatively, we can keep the platform classloader and throw a `ClassNotFoundException` if the resource can not be found, notifying modlauncher to load the class and use [`computeHierarchyFromClass`](https://github.com/McModLauncher/modlauncher/blob/6d11a6f010d495d58fdb34892bd1caed49d8eb9c/src/main/java/cpw/mods/modlauncher/TransformerClassWriter.java#L157) instead.

2022-03-28 18:19 UTC, OrionDevelopment commented
I know how it works, my problem is that the call to `ClassLoader.getSystemClassLoader()` gives access to a classloader which is not in module mode.
And that is something we should prevent.

2022-03-29 20:57 UTC, OrionDevelopment requested changes

2022-03-29 20:57 UTC, OrionDevelopment commented on src/main/java/cpw/mods/cl/ModuleClassLoader.java
> +                try (var is = this.parentLoaders.get(pname).getResourceAsStream(cname)) {
This is indeed a good idea, since this would else pipe system classes potentially through transformers.
And the call site takes care of this dynamically.

2022-03-29 21:23 UTC, Su5eD commented on src/main/java/cpw/mods/cl/ModuleClassLoader.java
>          }
Since an `IOException` would be fatal for reading the resource, could we throw the `ClassNotFoundException` immediately, using the caugth exception as the cause?

2022-03-29 21:31 UTC, LexManos commented on src/main/java/cpw/mods/cl/ModuleClassLoader.java
>          }
No, because FileNotFound is a IOException that is not a fatal thing. As transformers can create the class.

2022-03-29 21:32 UTC, LexManos commented on src/main/java/cpw/mods/cl/ModuleClassLoader.java
>          return maybeTransformClassBytes(bytes, name, context);
The check needs to happen AFTER maybeTransformClassBytes

2022-03-31 09:09 UTC, OrionDevelopment commented
This looks much better now, once I figure out how to properly test this stuff, I will pull it out of draft and start the triaging and testing procedure....

2022-04-11 14:23 UTC, OrionDevelopment commented
Testing procedures have been setup.
Last call for this PR before I merge it in a couple of days.

2022-05-23 11:53 UTC, merged