Refactor `SecureJar` implementation and add package exclusions
McModLauncher/securejarhandler pull request #47
Opened 2023-11-11 12:49 UTC by Technici4n

# Add `SecureJarBuilder`
In preparation for the package exclusions and other future additional `SecureJar` parameters, deprecate the old `from` methods for removal, and add a builder instead.

# Split implementation across new `JarContents` and `JarSigningData`
The motivation for this change is that usually we need access to some of the jar's contents when building the `JarMetadata`. Before this change, this is done by passing an incomplete `SecureJar` to the jar metadata factory in the constructor of `SecureJar`. This makes it very hard to reason about the code, because we don't know which parts of `SecureJar` can be safely referenced in the metadata construction, and we also don't know when the metadata can be used inside of `SecureJar`.

To fix this, I moved the methods needed for constructing the metadata to a new interface called `JarContents`. The builder was updated accordingly.

# Add option to exclude some folder from the package scan
Finally, I also added the option to exclude some folders from the package scan. This will be useful to skip the `assets` and `data` folders of some mods. Some mods have a LOT of assets (for example Continuity+), and scanning those can take a few seconds of startup time.

# Documentation
I tried to document many methods I encountered, to break the tradition of SJH being completely undocumented... :)

# Future work
I will make another PR to make the package scan parallel (across different jars)... but for now I think this PR is large enough. :)

# TODO
- [ ] Actually test with mods.

2023-11-12 16:40 UTC, Matyrobbrt requested changes
Mostly pendantic documentation complaints.

2023-11-12 16:40 UTC, Matyrobbrt commented on src/main/java/cpw/mods/jarhandling/JarContents.java
> +     * Gets the manifest of the jar.
```suggestion
     * {@return the manifest of the jar}
```

2023-11-12 16:40 UTC, Matyrobbrt commented on src/main/java/cpw/mods/jarhandling/JarContents.java
> +     * Gets all the packages in the jar.
```suggestion
     * {@return all the packages in the jar}
```

2023-11-12 16:40 UTC, Matyrobbrt commented on src/main/java/cpw/mods/jarhandling/JarContentsBuilder.java
> +     * Sets the paths for the files of this jar.
```suggestion
     * Sets the root paths for the files of this jar.
```

2023-11-12 16:40 UTC, Matyrobbrt commented on src/main/java/cpw/mods/jarhandling/JarContentsBuilder.java
> +    public JarContentsBuilder pathFilter(@Nullable BiPredicate<String, String> pathFilter) {
Can you move the bipredicate to its own FI custom interface for better documentation?

2023-11-12 16:40 UTC, Matyrobbrt commented on src/main/java/cpw/mods/jarhandling/SecureJar.java
> +    // The members below are deprecated for removal - use SecureJarBuilder instead!
And this isn't a javadoc because..?

2023-11-12 16:40 UTC, Matyrobbrt commented on src/main/java/cpw/mods/jarhandling/impl/JarContentsImpl.java
> +        this.ignoredRootPackages.addAll(List.of(ignoredRootPackages)); // And additional user-provided packages
The `ignoredRootPackages` should just be a `Set` in the constructor, even in the builder.

2023-11-12 16:40 UTC, Matyrobbrt commented on src/main/java/cpw/mods/niofs/union/UnionFileSystem.java
>      private final BiPredicate<String, String> pathFilter;
Same as above, use a custom FI implementation.

2023-11-12 18:59 UTC, Technici4n commented on src/main/java/cpw/mods/jarhandling/SecureJar.java
> +    // The members below are deprecated for removal - use SecureJarBuilder instead!
Because this comment applies to all of them, and I expect anyone encountering this to actually go read the source code...

2023-11-12 19:01 UTC, Technici4n commented on src/main/java/cpw/mods/jarhandling/impl/JarContentsImpl.java
> +        this.ignoredRootPackages.addAll(List.of(ignoredRootPackages)); // And additional user-provided packages
Done

2023-11-13 10:03 UTC, Technici4n commented on src/main/java/cpw/mods/jarhandling/JarContentsBuilder.java
> +    public JarContentsBuilder pathFilter(@Nullable BiPredicate<String, String> pathFilter) {
Done - I only moved to the new interface for `JarContentsBuilder` to avoid making this PR even larger again. ;)

2023-11-13 10:03 UTC, Technici4n commented on src/main/java/cpw/mods/niofs/union/UnionFileSystem.java
>      private final BiPredicate<String, String> pathFilter;
The FI is created, but moving more stuff to it will be in another PR.

2023-11-15 14:17 UTC, Su5eD approved these changes

2023-11-16 10:30 UTC, Matyrobbrt approved these changes

2023-11-16 12:07 UTC, merged