Remove the `notExistingPath` check and use a proper lazy streams
McModLauncher/securejarhandler pull request #50
Opened 2023-11-16 07:42 UTC by Matyrobbrt

The `!= notExistingPath` doesn't do anything, and the `newDirStream` method would accumulate the results in a list, which is not efficient for dir streams that early-exit. Streams are meant to be lazy.

2023-11-16 09:34 UTC, marchermans commented
@cpw This was your code path, and I am trying to understand why it exists. Is there a reason why this uses a custom path?

2023-11-16 11:36 UTC, Technici4n commented on src/main/java/cpw/mods/niofs/union/UnionFileSystem.java
> +                final Path realPath = toRealPath(base, path);
Nit: Why add `final` everywhere? It's visual noise imo ;)

2023-11-16 11:50 UTC, Technici4n requested changes

2023-11-16 16:02 UTC, Matyrobbrt commented on src/main/java/cpw/mods/niofs/union/UnionFileSystem.java
> +            stream = Stream.concat(stream, StreamSupport.stream(ds.spliterator(), false)
SJH does not pull in Guava.

2023-11-16 16:04 UTC, Technici4n commented on src/main/java/cpw/mods/niofs/union/UnionFileSystem.java
> +            stream = Stream.concat(stream, StreamSupport.stream(ds.spliterator(), false)
Oh lol you're right... 🤦 Maybe `Stream.of(...).flatMap(x -> x)`?

2023-11-16 16:06 UTC, Matyrobbrt commented on src/main/java/cpw/mods/niofs/union/UnionFileSystem.java
> +                    .filter(p -> testFilter(p, bp))
No, note the parentheses
> stream = Stream.concat **(** stream, StreamSupport.stream(ds.spliterator(), false)
        .filter(p -> testFilter(p, bp) **)**

2023-11-16 16:08 UTC, Matyrobbrt commented on src/main/java/cpw/mods/niofs/union/UnionFileSystem.java
> +            stream = Stream.concat(stream, StreamSupport.stream(ds.spliterator(), false)
It's probably less efficient doing it that way by then.

2023-11-16 17:53 UTC, Technici4n commented on src/main/java/cpw/mods/niofs/union/UnionFileSystem.java
> +                    .filter(p -> testFilter(p, bp))
Ah yeah. Maybe you could keep the inner stream in a different variable?

```java
Stream<UnionPath> basePathStream = StreamSupport.stream(...);
stream = Stream.concat(basePathStream, stream);
```

2023-11-16 17:57 UTC, Technici4n commented on src/test/java/cpw/mods/niofs/union/TestUnionFS.java
> +            assertEquals(foundFiles, List.of(
I don't know if the order is reliable here? Fine by me but this might be an implementation detail of one of the file systems?

2023-11-16 18:00 UTC, Matyrobbrt commented on src/test/java/cpw/mods/niofs/union/TestUnionFS.java
> +            assertEquals(foundFiles, List.of(
It seems to be as the test passes locally (windows) and on CI (ubuntu)

2023-11-17 13:30 UTC, Technici4n commented on src/main/java/cpw/mods/niofs/union/UnionFileSystem.java
> +                    .map(this::fastPath));
Can you replace all of this by a single `map` call to a new stream-free helper method? In my testing this seems to give a bit of a performance boost (maybe 10-20%).

```java
.map(other -> fastPath(isSimple ? other : bp.relativize(other)))

    /**
     * Create a relative UnionPath from the path elements of the given {@link Path}.
     */
    private UnionPath fastPath(Path pathToConvert) {
        String[] parts = new String[pathToConvert.getNameCount()];

        for (int i = 0; i < parts.length; i++) {
            parts[i] = pathToConvert.getName(i).toString();
        }

        return fastPath(parts);
    }
```

2023-11-17 13:30 UTC, Technici4n commented on src/test/java/cpw/mods/niofs/union/TestUnionFS.java
> +            assertEquals(foundFiles, List.of(
Alright

2023-11-17 13:33 UTC, Technici4n commented on src/main/java/cpw/mods/niofs/union/UnionFileSystem.java
> +                    .filter(p -> testFilter(p, bp))
Not resolved. :P 🔪

2023-11-17 15:32 UTC, Technici4n commented on src/main/java/cpw/mods/niofs/union/UnionFileSystem.java
> +                    closeable.close();
Should this handle the case of one of the closeables throwing an exception?

2023-11-17 15:33 UTC, Matyrobbrt commented on src/main/java/cpw/mods/niofs/union/UnionFileSystem.java
> +                    closeable.close();
Why would it? The close method throws an exception so that you can propagate it and let the caller handle it.

2023-11-17 15:36 UTC, Technici4n commented on src/main/java/cpw/mods/niofs/union/UnionFileSystem.java
> +                    closeable.close();
Maybe
```java
                List<IOException> exceptions = new ArrayList<>();
                
                for (Closeable closeable : closeables) {
                    try {
                        closeable.close();
                    } catch (IOException e) {
                        exceptions.add(e);
                    }
                }
                
                if (!exceptions.isEmpty()) {
                    IOException aggregate = new IOException("Failed to close some streams in UnionFileSystem.newDirStream");
                    exceptions.forEach(aggregate::addSuppressed);
                    throw aggregate;
                }
```
?

2023-11-17 15:37 UTC, Technici4n commented on src/main/java/cpw/mods/niofs/union/UnionFileSystem.java
> +                    closeable.close();
> Why would it? The close method throws an exception so that you can propagate it and let the caller handle it.

Yeah I meant that we should still (attempt to) close the other closeables if one throws an exception.

2023-11-17 15:37 UTC, Matyrobbrt commented on src/main/java/cpw/mods/niofs/union/UnionFileSystem.java
> +                    closeable.close();
I suppose.

2023-11-17 15:39 UTC, Technici4n commented on src/main/java/cpw/mods/niofs/union/UnionFileSystem.java
> +                final Path realPath = toRealPath(base, path);
(you can resolve this)

2023-11-17 15:39 UTC, Technici4n approved these changes

2023-11-17 15:51 UTC, Matyrobbrt commented
> @cpw This was your code path, and I am trying to understand why it exists. Is there a reason why this uses a custom path?

The custom path is left-over code from the [initial implementation](https://github.com/noeppi-noeppi/securejarhandler/commit/f475b5d57d19603b64bd23f1d7bd035de1509fd3#diff-40d9c8c4e5bd1b56b8dfccb981a57bd6fef5c624799bfa7bd799922ff98673b5R176), when a path filter that wouldn't match will return the `notExistingPath`. The whole concept has since been abandoned, with non-valid paths simply being skipped. The `notExistingPath` is safe to remove now.

2023-11-17 15:55 UTC, Technici4n commented
Note: just tested this on ATM9, loads fine as expected.

2023-11-17 19:31 UTC, Su5eD approved these changes

2023-11-17 19:59 UTC, merged