Update to Java 21
McModLauncher/securejarhandler pull request #69
Opened 2024-04-12 16:09 UTC by Gaming32

This removes the `ZipFileSystem.exists` hack and implements `FileSystemProvider.readAttributesIfExists` and `FileSystemProvider.exists`. While I was working on this, I also improved the #63 optimization in `readAttributes` by passing already known attributes.

2024-04-18 20:40 UTC, Technici4n commented
The `UnionFS` changes look good. The gradle update needs validation still.

2024-04-18 21:03 UTC, Matyrobbrt commented on sjh-jmh/build.gradle
> +        languageVersion = JavaLanguageVersion.of(21)
Since it's used twice, I'd make the java version a property.

2024-04-25 19:00 UTC, marchermans requested changes

2024-04-25 19:00 UTC, marchermans commented on build.gradle
>  buildscript {
The removal of the imports prevents my IDE from importing this project.

2024-04-25 19:25 UTC, marchermans approved these changes

2024-04-25 19:28 UTC, merged